### PR TITLE
Fixed typos, adjusted width

### PR DESCRIPTION
**Pull request by lFenix**
Fixed problems in #486

### CODE REVIEW

**Comment by aonez** [comment]
Thanks again @lFenix! There you have the build: [Keka-Czech-r2.7z](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-Czech-r2.7z)

**Comment by lFenix** [comment]
Thanks for the build again 😊 Can I have another request?

What's the ID of this dropdown?
image

I thought I've already fixed the grammar mistake in it in the last commit, but apparently not 😩

**Comment by aonez** [comment]
https://github.com/lFenix/Keka/blob/c390e8a9e34f589ed7798346ca9e35b7cec9396d/Translations/cs.lproj/preferences.strings#L71-L78
```
/* Class = "NSMenuItem"; title = "Ask each time"; ObjectID = "279"; */
"279.title" = "Pokaždé se zeptat";
/* Class = "NSMenuItem"; title = "Next to original file"; ObjectID = "280"; */
"280.title" = "Stejná, jako výchozí soubory";
/* Class = "NSMenuItem"; title = "Custom folder..."; ObjectID = "281"; */
"281.title" = "Vybrat složku...";
```

https://github.com/lFenix/Keka/blob/c390e8a9e34f589ed7798346ca9e35b7cec9396d/Translations/cs.lproj/preferences.strings#L113-L120

```
/* Class = "NSMenuItem"; title = "Ask each time"; ObjectID = "357"; */
"357.title" = "Pokaždé se zeptat";
/* Class = "NSMenuItem"; title = "Next to original file"; ObjectID = "358"; */
"358.title" = "Stejné, jako výchozí soubory";
/* Class = "NSMenuItem"; title = "Custom folder..."; ObjectID = "359"; */
"359.title" = "Vlastní cesta...";
```

**Comment by lFenix** [comment]
Thank you again, that finally fixed it 😊 I also found out how to test the localization on my machine, so I will no longer spam you with build requests 😅

I'll open one more pull request, and that should be it for this release

**Comment by aonez** [comment]
> I also found out how to test the localization on my machine

Yeah maybe resigning it should be enough 🤓

**Pull request merged**
