### PR TITLE
Update Korean translation

### PR DESCRIPTION
**Pull request by sboh1214**

### CODE REVIEW

**Comment by aonez** [comment]
Thanks you so much! Don't you want to appear in the credits?

https://github.com/aonez/Keka/blob/45f7308321b40de1ba53f30b674f039f56218fc8/Translations/Common/Translators.html#L95-L100

**Comment by sboh1214** [comment]
@aonez Thanks for notifying me about credits! I didn't know that :)

**Comment by aonez** [comment]
@sboh1214 I just found this line:
https://github.com/aonez/Keka/blob/3eae687aacb52dbbc1b179ed6a480d402cff4f21/Translations/ko.lproj/Localizable.strings#L127

I've received a translation from another user in the mail, and merged with the current translation, in case you want to check it out -> https://github.com/aonez/Keka/commit/6ab715443edd6ae21ecee4c78692be960db5f46d.

In those there're some strings not translated, maybe you can take a look at them 🧐:
https://github.com/aonez/Keka/blob/6ab715443edd6ae21ecee4c78692be960db5f46d/Translations/ko.lproj/Localizable.strings#L186-L187

**Comment by sboh1214** [comment]
@aonez I'm glad there are many Korean translators. As you pointed out, I and Rockmc? didn't translate "Error code", "nPreferences" , and "source/s folder/s". I'll translate in my spare time and submit new PR. Thanks!

**Pull request merged**
