### PR TITLE
Add Vietnamese language

### PR DESCRIPTION
**Pull request by 1234hdpa**
+ Add Vietnamese language.
+ Translated by 1234hdpa on Github.

Any spelling and grammar corrections are welcome! :D

### CODE REVIEW

**Comment by aonez** [comment]
Thanks a lot @1234hdpa!!!

Don't forget to add yourself to the translators list:

https://github.com/aonez/Keka/blob/e6ebf1d0fb801ab5a5c40d81394227a8dd2ac7b6/Translations/Common/Translators.html#L7-L10

**Comment by 1234hdpa** [comment]
Just finish the Vietnamese translation for website. Please check it out :) 
Thanks.

**Comment by aonez** [comment]
The web is already up!

**Comment by aonez** [comment]
@1234hdpa here you have a build with your translation: [Keka-VI-1234hdpa.7z](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-VI-1234hdpa.7z)

**Pull request merged**
