### PR TITLE
New BR translations

### PR DESCRIPTION
**Pull request by vitu**
Cheers!

### CODE REVIEW

**Comment by aonez** [comment]
Thanks Vitu! Salut :)

**Comment by aonez** [comment]
@vitu I'll be updating `pt-PT` project with your changes from now on since there's no active maintainer for that localization. Hopefully this is 👍🏼 for you.

**Comment by vitu** [comment]
Hum, I don't know… maybe it would be better to keep strings in English until you have someone, as PT and BR often have different spelling, grammar and syntax, among other particularities. What do you say?

**Comment by aonez** [comment]
I'm thinking about this because there's no Portuguese update since 2018 and it was a puntual contribution based on your translation. So using your translation for parts that are in English might be enough for most Portuguese speakers and may trigger some to change Brazilian wording (update the translation). Only if you're ok with it, if not I'll keep them in English.

**Comment by vitu** [comment]
Oh, I wasn't aware of that! Thanks for letting me know. Makes sense then to keep it there to trigger a potential collaboration. I'm just trying to avoid any claims that my translation might be adequate to pt-PT.

**Pull request merged**
