### PR TITLE
Update InfoPlist.strings

### PR DESCRIPTION
**Pull request by rakekniven**
Update of german strings.

Signed-off-by: Mark Ziegler <mark.ziegler@rakekniven.de>

### CODE REVIEW

**Comment by rakekniven** [comment]
Other files will be updated the next days in separate PR.

**Comment by aonez** [comment]
Thanks a lot @rakekniven!

**Comment by aonez** [comment]
@rakekniven I've received some pull request form another user that updated the German translation. Since I've seen you've already done some work in your https://github.com/rakekniven/Keka/tree/patch-2 branch, I'll wait until you're done.

**Comment by aonez** [comment]
@rakekniven just merged the ready pull requests since those used "Apple like" strings for system menu items. I'll add you to the translators list anyway, and feel free to improve the translation whenever you can :)

**Comment by rakekniven** [comment]
Here is my work. See https://github.com/aonez/Keka/pull/282

**Pull request merged**
