### PR TITLE
Terminology Update for BR

### PR DESCRIPTION
**Pull request by vitu**
Updated “Zoom” and “Download” translations to conform with macOS Catalina terminology updates.

Also made some cosmetic changes on website translation.

### CODE REVIEW

**Comment by aonez** [comment]
Thanks @vitu! Curious about the Downloads, I suppose it's becoming the common way to call it there?

**Comment by aonez** [comment]
Just pushed v1.1.20 yesterday, so this will need to wait to v1.1.21. Already have a bug fixed for that one, so maybe in a week :)

**Comment by vitu** [comment]
> Thanks @vitu! Curious about the Downloads, I suppose it's becoming the common way to call it there?

Actually, people have always used the new terms… it just took a while for the official terminology to catch up and change “transferência” (noun) to download, and “transferir” (verb) to baixar.

**Comment by vitu** [comment]
> Just pushed v1.1.20 yesterday, so this will need to wait to v1.1.21. Already have a bug fixed for that one, so maybe in a week :)

That's perfectly fine. ¡Salud!

**Pull request merged**
