### PR TITLE
Pull request for helping in Bulgarian translation

### PR DESCRIPTION
**Pull request by m-dragoev**
I will help for Bulgarian translation, if needed :)

### CODE REVIEW

**Comment by aonez** [comment]
First of all thanks for the translation @m-dragoev!

Why did you added the Dependency Review action? I'm holding the merge because of that file.

**Comment by m-dragoev** [comment]
> First of all thanks for the translation @m-dragoev!
> 
> 
> 
> Why did you added the Dependency Review action? I'm holding the merge because of that file.

I created this file by mistake.  I also want to say that I am working on supplementing more things in the translation so that there is no untranslated line.

**Comment by aonez** [comment]
Let me know when you're done and also don't forget to remove `.github/workflows/dependency-review.yml)`. Thanks a lot @m-dragoev!

**Comment by m-dragoev** [comment]
> Let me know when you're done and also don't forget to remove `.github/workflows/dependency-review.yml)`. Thanks a lot @m-dragoev!

You're welcome @aonez !

**Comment by m-dragoev** [comment]
@aonez , translation is complete :)

**Pull request merged**
