### PR TITLE
Minor changes to texts

### PR DESCRIPTION
**Pull request by anosidium**

### CODE REVIEW

**Comment by anosidium** [comment]
British English Localisation.

**Comment by gingerbeardman** [comment]
Some of this doesn't read well. No better than the original text.

> What is more to do here?

And please make sure to capitalise terms the same way as macOS, eg. bin -> Bin

I have not read all changes.

**Comment by anosidium** [comment]
Punctuations are important. It may not be significant but it improve the clarity. Maybe that one could be dismissed but this one is important.

> So, where is the source code

is a question and therefore requires a question mark.

I have updated the capitalisation of the word bin to Bin.

**Comment by aonez** [comment]
@anosidium, please remove the README changes so I can merge the en-GB.lproj

**Comment by anosidium** [comment]
Done! By the way, macOS Catalina have a better English localisation. The Trash has been renamed to Bin.

**Comment by aonez** [comment]
Thanks @anosidium! The pull needed some tweaking, there were some strings removed and some comments and keys translated. Maintenance should be pretty easy from now on 😊

**Pull request merged**
