### PR TITLE
Fix Russian strings

### PR DESCRIPTION
**Pull request by NickKaramoff**
That was hard considering how long some Russian words are :sweat_smile:

### CODE REVIEW

**Comment by hugonote** [comment]
These lines would be on links/buttons, wouldn't they? So I think there should still be a verb of some kind.
It may sound better, but out of context it's not clear what it means.

**Comment by aonez** [comment]
They are titled and descriptions, not links :)

**Comment by hugonote** [comment]
Okay, it's just that in my PR #968 I made edits to that section as well.
Since these are only descriptions, it is better to take them from this PR rather than mine.

**Comment by aonez** [comment]
Thanks for the effort @NickKaramoff 👏🏼

**Pull request merged**
