### PR TITLE
Minor corections & bugs report

### PR DESCRIPTION
**Pull request by lboratynski**
I've tested a latest beta version and made some changes in translation. Also noticed a few problems:

**1. Missing strings in translation files.**

**2. Compression tab is not working.**

PS.
I've noticed that there is a confilict in Translations/pl.lproj/preferences.strings related to missing strings. Let me know how we can fix this.

### CODE REVIEW

**Comment by aonez** [comment]
There's a conflict because you did not updated your fork with the latest version of the repository. I've made this changes (that added the missing strings):

https://github.com/aonez/Keka/commit/e07a00314ef51d23b4b4eb393e7c378e2ac77192#diff-46243f8b0ed652041e3584d20e31fa96
https://github.com/aonez/Keka/commit/e07a00314ef51d23b4b4eb393e7c378e2ac77192#diff-cd5e22dc12081db4e856edbbf53f49a0

And this last one, that fixed the issue in the preferences: https://github.com/aonez/Keka/commit/94fb7b32666454bc3022c3bb4ab0f0364aef58c2

Please update your fork first to the latest state of this repository, and then apply again your changes. Let me know if you need help with that, I know it can be a little tricky sometimes.

Thanks @lboratynski!

**Comment by lboratynski** [comment]
Alright, gonna fix this as soon as possible.

**Comment by lboratynski** [comment]
I was unable to update a repository and avoid conflicts, so I deleted it, forked and edited again. Hope it's gonna work now. Please mark this request as Closed.

**Comment by aonez** [comment]
> I was unable to update a repository and avoid conflicts

Told you it is sometimes a headache... Sorry for the trouble. Closing this one.

**Pull request closed without merging**
