### PR TITLE
Polish translation for Keka

### PR DESCRIPTION
**Pull request by lboratynski**
This is a Polish translation for Keka. Any feedback is appreciated...

### CODE REVIEW

**Comment by aonez** [comment]
Thank a lot @lboratynski! Gonna try it now!

**Comment by aonez** [comment]
@lboratynski can the context menu item say "Compress with Keka" instead of only "Archive...", that way it is more clear to the user and won't get confused with the macOS own item.

**Comment by lboratynski** [comment]
@aonez, hope it's gonna be useful. On context menu, sure! Just give me a second.

**Comment by aonez** [comment]
By the way, I have three new versions of the context menu item. Will let you know as soon as I update them on the repository. They are for Keka v1.1.0, not for earlier versions.

**Comment by aonez** [comment]
@lboratynski the Keka translation is missing the "Localizable.strings" file... Maybe you've missed to upload it?

**Comment by lboratynski** [comment]
Yep, it's missing cause I didn't translate it yet. If it's a must for a proper translation, I'll prepare this asap.

**Comment by aonez** [comment]
Sure, without this file the translation is partial. Take your time! Thanks a lot @lboratynski

**Comment by lboratynski** [comment]
Alright, just updated a repo with changes in context-menu. _Compress with Keka_ is translated to _Keka - dodaj do archiwum_ which basically means: Keka - add to an archive. Gonna translate & update Localizable.strings as soon as possible.

**Comment by aonez** [comment]
@lboratynski if you want send me an email to info@kekaosx.com and I give you some tips 👍

**Pull request merged**
