### PR TITLE
Update CHS translations

### PR DESCRIPTION
**Pull request by maxsky**
Strictly distinguish these words: extract, archive, compress, uncompress and tarball.

### CODE REVIEW

**Comment by aonez** [comment]
Thanks @maxsky! I wasn't expecting this 🤯 overkill!

**Comment by aonez** [comment]
Here a build @maxsky, in case you want to see all the changes live:
[Keka-v1.2.8-r4413.7z](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.2.8-r4413.7z)

**Comment by maxsky** [comment]
> Here a build @maxsky, in case you want to see all the changes live:
> [Keka-v1.2.8-r4413.7z](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.2.8-r4413.7z)

cap

Great, but is this part not translated?

**Comment by aonez** [comment]
Thanks a lot @maxsky! I don't know how I did not noticed this earlier, the translations are there but are not applied. Fixed right away!

Screenshot 2021-01-26 at 17 33 19

Can you check those? MAS does not allow the use of emojis, so sadly I can't use the strings with the ☕️...
https://github.com/aonez/Keka/blob/439dfcc944d39ee82c41133e6ffdbde5a76909f6/Translations/zh-Hans.lproj/Localizable.strings#L218-L227

**Comment by maxsky** [comment]
> Thanks a lot @maxsky! I don't know how I did not noticed this earlier, the translations are there but are not applied. Fixed right away!
> 
> Screenshot 2021-01-26 at 17 33 19
> 
> Can you check those? MAS does not allow the use of emojis, so sadly I can't use the strings with the ☕️...
> https://github.com/aonez/Keka/blob/439dfcc944d39ee82c41133e6ffdbde5a76909f6/Translations/zh-Hans.lproj/Localizable.strings#L218-L227

lol, these very interesting locally translations, sure, I will replace emojis to words.

**Pull request merged**
