### PR TITLE
New strings translated!

### PR DESCRIPTION
**Pull request by vitu**
Cheers!

### CODE REVIEW

**Comment by aonez** [comment]
Gracias @vitu! Maybe you can also translate these new strings: https://github.com/aonez/Keka/commit/279808b94cdc1efa2996317e60861ee765f2bdda

Salut!

**Comment by vitu** [comment]
It's done now (or so I believe). Salut!

**Comment by aonez** [comment]
Thanks a lot @vitu!

**Comment by aonez** [comment]
Just found out the files were not placed in the right place... I'm merging properly this update in 1.2.55 😅

**Comment by vitu** [comment]
Awesome! Please let me know if there's anything pending!

**Pull request merged**
