### PR TITLE
Update for Polish translation

### PR DESCRIPTION
**Pull request by lboratynski**
Translated all strings to Polish, tested in Xcode, pushed wrong files, then corrected some strings. Anyway, correct still might contain some typos to be corrected…

### CODE REVIEW

**Comment by aonez** [comment]
@lboratynski how you want to appear on the credits? as @lboratynski? (you can let me know by mail, also)

**Comment by lboratynski** [comment]
Sure. That's fine for me.

W dniu niedz., 20.08.2017 o 21:10 aONe <notifications@github.com>
napisał(a):

**Comment by aonez** [comment]
In case you want to update it, here it is:

https://github.com/aonez/Keka/blob/master/Translations/Common/Translators.html

**Comment by lboratynski** [comment]
I've updated a translation to fit new beta-release and made a pull request.
Please check if it's alright, cause there are some errors.

W dniu niedz., 20.08.2017 o 21:40 aONe <notifications@github.com>
napisał(a):

**Comment by aonez** [comment]
@Luke I'm unable to check this right now, let me check it out next week.

**Comment by lboratynski** [comment]
Sure. I'll keep in touch.

W dniu pt., 25.08.2017 o 12:14 aONe <notifications@github.com> napisał(a):

**Pull request merged**
