### PR TITLE
Turkish web translation by @bariskayadelen

### PR DESCRIPTION
**Pull request by bariskayadelen**
Turkish web page translation.

### CODE REVIEW

**Comment by aonez** [comment]
Thanks a lot @bariskayadelen!

**Comment by aonez** [comment]
@bariskayadelen just published this on the web! On Monday/tuesday update 1.1.3 will come with your translation :)

**Comment by bariskayadelen** [comment]
I checked the webpage. It looks good. :)

Have you checked the translate web page, crowdin.com? You can find more translator via Crowdin.

**Comment by aonez** [comment]
Never seen that one. Is paid, though. Forget about the Monday/Tuesday release, the Apple Review team has other plans 🤯

**Comment by bariskayadelen** [comment]
Crowdin is free for Open Source Projects. What's going on? What are the Apple Review team' plans?

**Comment by aonez** [comment]
Just noticed I've implemented wrongly the update, your translation is coming in 1.1.4! Sorry!

**Pull request merged**
