### PR TITLE
Translate Keka to Norwegian Bokmål

### PR DESCRIPTION
**Pull request by 16patsle**
Hi there! I've translated Keka to Norwegian Bokmål. I'm pretty sure I haven't messed up any files, but still, let me know if there is anything that needs changing.

### CODE REVIEW

**Comment by aonez** [comment]
Thanks a lot @16patsle! I'll merge this ASAP. This will not be public until 1.1.6, since I'm having trouble right now with 1.1.5 and Apple.

**Comment by aonez** [comment]
@16patsle here you can test a build with the translation: https://t.keka.io/Keka-nb.7z

I was unable to make Credits.html to work, don't know yet why.

**Comment by 16patsle** [comment]
@aonez Tested the build, and everything seems to be working as it should. I did some limited testing with compressing and extracting, and everything seems to be in order. I did find a typo I didn't notice earlier in the preferences though, under File Access. Would it be easiest for you to fix it directly, or should I fix it and make another PR?

"Her kan du velge mappene ti vil gi Keka tilgan til." should be "Her kan du velge mappene du vil gi Keka tilgang til."

**Comment by aonez** [comment]
Thanks @16patsle! Already fixed that line. If you find something else, just let me know or make a new PR.

**Comment by aonez** [comment]
Just realized the web translation wasn't up... Fixed now! Thanks again @16patsle!

**Pull request merged**
