### PR TITLE
check CHS translation

### PR DESCRIPTION
**Pull request by maxsky**
Sorry I'm late.

### CODE REVIEW

**Comment by maxsky** [comment]
not found ios.keka.io web page translation file, its missed to add? ;)

**Comment by aonez** [comment]
Thanks @maxsky!!!

The iOS files are here: https://github.com/aonez/Keka/tree/master/Translations-iOS

If you have Xcode try the `xloc` files. If not (or you don't like those) use the `Alternative-Strings-Files`.
I've used ChatGPT for the first translation as a test, so expect it not to be the best.

**Comment by aonez** [comment]
Oh sorry I've misread! You mean the web, let me check.

**Comment by maxsky** [comment]
> Oh sorry I've misread! You mean the web, let me check.

lol :)

**Comment by aonez** [comment]
The files are updated now 👍 

https://github.com/aonez/Keka/commit/871b1e8ed5849c27530856cc90d7f65701b4e8aa

**Comment by maxsky** [comment]
All completed

**Comment by aonez** [comment]
Web updated: https://ios.keka.io

**Pull request merged**
