### PR TITLE
Add upstreamSync action

### PR DESCRIPTION
**Pull request by ferben**
Action template for contributors.
Action which sync contributor's own fork with upstream repo every afternoon.

### CODE REVIEW

**Comment by aonez** [comment]
Nice! Let's try it :)

**Comment by ferben** [comment]
Yes, it works!

### How to
Simple, go to Actions in your forked repo, add action "Sync Upstream" (upstreamSync.yml). This is it, no other action needed.
Everyday your fork will be synced with upstream aones/Keka.

**Comment by aonez** [comment]
Did it worked?

**Comment by ferben** [comment]
> Did it worked?

Yes it works

**Comment by reneleonhardt** [comment]
1. Wouldn't it be logical to only sync forks, not the original repo?
https://github.com/aonez/Keka/actions/workflows/upstreamSync.yml
```yaml
if: ${{ github.repository != 'aonez/Keka' }}
```

2. Be aware that the action isn't maintained anymore since 2022:
https://github.com/dabreadman/sync-upstream-repo/pull/8
This should do the trick:
```yaml
- run: gh repo sync
```
If you prefer an action, https://github.com/ws2git/gh-repo-action runs gh for you.

**Pull request merged**
