### PR TITLE
Added Czech translation

### PR DESCRIPTION
**Pull request by lFenix**
Translated all files into Czech.

### CODE REVIEW

**Comment by aonez** [comment]
Thanks a lot @lFenix!

**Comment by aonez** [comment]
In case you want to test, here a build: [Keka-Czech.tar.7z](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-Czech.tar.7z)

**Comment by lFenix** [comment]
Hey @aonez! Thank you for the build, I found some minor typos in it that I fixed. I have a question though.

I'm a bit concerned about these labels being cut off:
image

I know there's this in Localizable.strings. Would setting it to any other value help, and if so, what are the recommended values?
image

**Comment by aonez** [comment]
> I'm a bit concerned about these labels being cut off

I'll fix that one for you

> I found some minor typos in it that I fixed

Cool! You'll do another pull?

**Comment by aonez** [comment]
> I'm a bit concerned about these labels being cut off

75.0 for `_ADVANCED_EXTRA_WIDTH_` it is

**Comment by lFenix** [comment]
I'll do another pull in a few minutes with both the fixed typos and the correct `_ADVANCED_EXTRA_WIDTH_` 😊

Can you send me another build after this next pull is merged so I can check everything again, to make sure everything looks good?

**Comment by aonez** [comment]
Sure @lFenix! Thanks again for this 😊

**Pull request merged**
