### PR TITLE
Long time, no update!

### PR DESCRIPTION
**Pull request by lboratynski**
Translation may contain slight grammatical errors or typos. Please let me know if you find one.

### CODE REVIEW

**Comment by aonez** [comment]
Thanks a lot @lboratynski! Maybe you can also update those new strings I've linked to this pull?

https://github.com/aonez/Keka/commit/ac91f498078672b6223e8cdd9c640d415b9b3940#r48452007
https://github.com/aonez/Keka/commit/dd4b5eb7cfa822a65ec06fb716b22fe3056b0cff#r48452033
https://github.com/aonez/Keka/commit/a07c3f67ae6a77e2e993325274b68facc51a51c2#r48452068

**Comment by aonez** [comment]
Thanks again @lboratynski!!! You don't need to create a new pull, your changes should appear here 😅

**Comment by lboratynski** [comment]
I haven't used GitHub for a long time, I might have forgotten something. Thanks! Let me know if you need anything.

**Comment by aonez** [comment]
My bad! I did not see those that were already translated 😅

**Pull request merged**
