### PR TITLE
German translation update

### PR DESCRIPTION
**Pull request by rakekniven**

### CODE REVIEW

**Comment by aonez** [comment]
This one has conflicts, please merge the current status first.

**Comment by rakekniven** [comment]
Done.

**Comment by aonez** [comment]
I'm gonna stick with the @iOSLaura version for now, since uses more Apple like strings for the menu items at least. Can't really review the other text 😓 Thanks a lot @rakekniven! Do you have any priority on how to appear on the credits?

https://github.com/aonez/Keka/blob/88ecb70f5e4b724478f3356ed46a03f158358cc0/Translations/Common/Translators.html#L31-L33

**Comment by rakekniven** [comment]
Does it mean that my branch is obselete?
It is fine for me.
Had a quick look at some strings and some wordings could be improved IMHO.
How to deal with it?

**Comment by aonez** [comment]
@rakekniven yes, you need to work from the current status from now on 👍🏼

**Pull request closed without merging**
