### PR TITLE
Hungarian translation added for website and iOS version

### PR DESCRIPTION
**Pull request by zetenynagy**
Added Hungarian translation for the website and the iOS app version. iOS app might need testing for a better understanding of context.

edit: sometime it might be worth cross-referencing with already existing Hungarian macOS translation, and combining the two for consistency?

### CODE REVIEW

**Comment by aonez** [comment]
Thank you so much @zetenynagy!! I'll publish a build on TestFlight right away.

> edit: sometime it might be worth cross-referencing with already existing Hungarian macOS translation, and combining the two for consistency?

I preferred to start fresh, just a few strings are reused. Note I'm working on the [next generation of Keka for macOS](https://github.com/aonez/Keka/issues/100#issuecomment-1827577006) that is based on the iOS version, so in the future iOS and macOS will share the same translation :)

**Comment by aonez** [comment]
Already published the changes in the website and released a build in TestFlight: https://testflight.keka.io/ios

You should look for version 1.2.5 (946), that one has your translation.

**Comment by aonez** [comment]
The TestFlight build is now ready (was being reviewed by Apple). Let me know if you have trouble finding it.

**Comment by zetenynagy** [comment]
Thanks! Today I checked the website and the iOS app - both have very minor grammatical errors or slight inconsistencies that became apparent just now, by seeing them in context. I will try to remedy these in the coming days.

**Pull request merged**
